version: '3.3'
services:
    postgres:
      build:
        context: services/postgres
        dockerfile: Dockerfile.development
      ports:
      - "5433:5433"
      env_file:
        - env/postgres.env

    app:
      build:
        context: services/app
        dockerfile: Dockerfile.development
      command: java -jar ./bot.jar
      env_file:
        - env/app.env
      image: 'bot-app'
      depends_on:
        - postgres
